=== Neanksl/XML2016/final_assignment/Mancala/gamestate.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--Andreas Eichner, Michael Conrads-->

<!ELEMENT winCount (#PCDATA)>
<!ELEMENT game (#PCDATA | board | players)*>
<!ELEMENT players (#PCDATA | turn | player)*>
<!ELEMENT pit (#PCDATA)>
<!ATTLIST pit id CDATA #IMPLIED>
<!ELEMENT turn (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT house (#PCDATA)>
<!ATTLIST house id CDATA #IMPLIED>
<!ELEMENT board (#PCDATA | layer)*>
<!ELEMENT layer (#PCDATA | pit | house)*>
<!ATTLIST layer position CDATA #IMPLIED>
<!ELEMENT player (#PCDATA | id | winCount)*>

=== Neanksl/XML2016/final_assignment/Mancala/gamestate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE mancala SYSTEM "GameState.dtd"> -->

<game>
    <board>
        <layer position="top">
            <house id="1">1</house>
            <house id="2">2</house>
            <house id="3">3</house>
            <house id="4">4</house>
            <house id="5">5</house>
            <house id="6">6</house>
            
            <store id="7">20</store>
        </layer>
        
        <layer position="bottom">
            <house id="8">12</house>
            <house id="9">11</house>
            <house id="10">10</house>
            <house id="11">9</house>
            <house id="12">8</house>
            <house id="13">7</house>
            
            <store id="14">10</store>
        </layer>
    </board>
    
    <players>
        <turn>1</turn>
        
        <player>
            <id>1</id>
            <winCount>2</winCount>
        </player>
        
        <player>
            <id>2</id>
            <winCount>0</winCount>
        </player>
    </players>
</game>

=== Neanksl/XML2016/final_assignment/Mancala/reference_gamestate_unused.xml
<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE game SYSTEM "./gamestate.dtd">
<?xml-stylesheet href="transform.xsl" type="text/xsl"?>
<game>
    <board>
        <layer position="top">
            <house id="1">3</house>
            <house id="2">3</house>
            <house id="3">3</house>
            <house id="4">3</house>
            <house id="5">3</house>
            <house id="6">3</house>
            
            <store id="7">0</store>
        </layer>
        
        <layer position="bottom">
            <house id="8">3</house>
            <house id="9">3</house>
            <house id="10">3</house>
            <house id="11">3</house>
            <house id="12">3</house>
            <house id="13">3</house>
            
            <store id="14">0</store>
        </layer>
    </board>
    
    <players>
        <turn>1</turn>
        
        <player>
            <id>1</id>
            <winCount>2</winCount>
        </player>
        
        <player>
            <id>2</id>
            <winCount>0</winCount>
        </player>
    </players>
</game>

=== Neanksl/XML2016/4/Mancala/gamestate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Andreas Eichner, Michael Conrads-->

<!DOCTYPE game SYSTEM "./gamestate.dtd">
<?xml-stylesheet href="transform.xsl" type="text/xsl"?>
<game>
    <board>
        <layer position="top">
            <pit id="1">3</pit>
            <pit id="2">3</pit>
            <pit id="3">3</pit>
            <pit id="4">3</pit>
            <pit id="5">3</pit>
            <pit id="6">3</pit>
            
            <house id="7">0</house>
        </layer>
        
        <layer position="bottom">
            <pit id="8">3</pit>
            <pit id="9">3</pit>
            <pit id="10">3</pit>
            <pit id="11">3</pit>
            <pit id="12">3</pit>
            <pit id="13">3</pit>
            
            <house id="14">0</house>
        </layer>
    </board>
    
    <players>
        <turn>1</turn>
        
        <player>
            <id>1</id>
            <winCount>2</winCount>
        </player>
        
        <player>
            <id>2</id>
            <winCount>0</winCount>
        </player>
    </players>
</game>
